name: Kind
on: [push, pull_request]
jobs:
  test-unit:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: 1.16
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide
